### ISSUE TITLE
Negate filter criteria

### ISSUE THREAD

**Issue by keram79** [CERT-BDF/TheHive#351] opened 2017-10-19 14:13 UTC
It is currently possible to filter cases e.g. by tag, say "show me all cases with tag "MISP". It might come in handy to be able to filter by "NOT tag", e.g. "show me all cases that are not shared with MISP", i.e. that *don't* have the "MISP" tag.

### Request Type
Feature Request

**Comment by nadouani** [comment] 2017-10-19 14:30
This a duplicate of #296

**Closed by nadouani** 2017-10-19 14:30 UTC
Labels: duplicate
