### ISSUE TITLE
Error message related to elasticsearch fielddata when clicking in tab "tasks"

### ISSUE THREAD

**Issue by typonino** [CERT-BDF/TheHive#322] opened 2017-09-27 10:12 UTC
Error message related to elasticsearch fielddata when clicking in tab "tasks

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu 16.04.3 LTS
| TheHive version / git hash   | 2.13.1
| Package Type              | DEB
| Browser type & version    | chrome

### Problem Description
When going to tab "tasks" in a case we see a red windows with error message " Fielddata is disabled on text fields by default. Set fielddata=true on [title] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead"

This error is also present in elasticsearch log file.
ElasticSearch Version is 5.6.1

### Steps to Reproduce
1. create a case
1. go to tasks tab

### Complementary information

![image](https://user-images.githubusercontent.com/18438405/30908152-0c75eea8-a37d-11e7-8bdc-99bdec5af93d.png)

**Comment by saadkadhi** [comment] 2017-09-28 05:30
Hi @typonino. We have not encountered such behavior on our end. We will try to reproduce it and if we can't we'll ask you for complementary details.

**Comment by To-om** [comment] 2017-10-02 08:24
This issue is duplicated with CERT-BDF/TheHive#311 and has been fixed in TheHive 2.13.1.

If you still have this issue with TheHive 2.13.1, you probably initialized your ElasticSearch index with TheHive 2.13.0.
Drop your index (`curl -XDELETE http://127.0.0.1:9200/the_hive_10`), it will be recreated without the mapping issue.

I close this issue, feel free to reopen it if the problem persists.

**Closed by To-om** 2017-10-02 08:24 UTC
Labels: bug

**Comment by FeisTy-H** [comment] 2017-10-11 13:31
Hi,
just downloaded the .OVA image file for testing purpose and the issue is still present on it. I guess it is linked to the version because it seems to be still the 2.13.0 whereas on the github training page it should be the 2.13.1 if I am not wrong. Can you confirm the OVA image still has the version with the issue ? 

By the way, so great work. thank you.

**Comment by garanews** [comment] 2017-10-13 06:26
I had same issue with OVA image, updated it, deleted ES index and everything now is fine.
