### ISSUE TITLE
the total alert counter is not properly updated in the alerts view

### ISSUE THREAD

**Issue by Rolinh** [CERT-BDF/TheHive#281] opened 2017-08-16 11:40 UTC
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Windows
| TheHive version / git hash   | 2.12.1
| Package Type              | Binary
| Browser type & version    | Firefox

### Problem Description

The total alert counter is not properly refreshed when new alerts arrive unless one refreshes the page. At the same time, the filtered alerts counter is properly refreshed. This means that in such a case, you may see something like "List of alerts (61 of 57)" as shown in the screenshot below.

### Steps to Reproduce

Wait for new alerts to show up in the alerts view without refreshing the page.

### Complementary information

![l_ef65 tmp](https://user-images.githubusercontent.com/1324157/29361365-956cbe38-8287-11e7-99c9-c8ac0ee46e23.PNG)

**Comment by nadouani** [comment] 2017-08-21 12:55
How did you get something like "(61 of 57)" ? What's the filter in your case?

**Comment by Rolinh** [comment] 2017-08-21 14:25
There are no filters.

**Comment by nadouani** [comment] 2017-08-21 14:27
Can you please provide me the steps to reproduce the issue? Thanks

**Comment by nadouani** [comment] 2017-08-21 14:30
Does this only occur with alerts coming from MISP or even for manually created alerts (using the alert APIs)?

**Comment by Rolinh** [comment] 2017-08-21 14:31
Well, it's written in the bug report in the "Steps to Reproduce" section: keep the alerts tab open and wait for new alerts to be created without refreshing the page.
If you can't reproduce with these instructions, maybe there is something else to it.

**Comment by nadouani** [comment] 2017-08-21 14:32
Well, If I ask the question, then it's probably because I cannot reproduce the issue with what has been said on the "Steps to Reproduce" section ;)

**Comment by Rolinh** [comment] 2017-08-21 14:33
I'll try to figure what else is needed to reproduce the issue and get back to you then ;).

**Comment by nadouani** [comment] 2017-08-21 14:33
Sure, thanks

**Comment by nadouani** [comment] 2017-08-29 13:07
Any updates for this one?

**Comment by Rolinh** [comment] 2017-09-08 13:31
It occurs from time to time but I'm unsure about how to reproduce it...
However, I believe the following change to be a possible fix as it changes the way the total counter is computed to how it's done [here](https://github.com/CERT-BDF/TheHive/blob/master/ui/app/views/components/header.component.html#L48) (which never showed a wrong value afaict):
```
diff --git a/ui/app/views/partials/alert/list.html b/ui/app/views/partials/alert/list.html
index e083799..0dfc4f8 100644
--- a/ui/app/views/partials/alert/list.html
+++ b/ui/app/views/partials/alert/list.html
@@ -2,7 +2,7 @@
     <div class="col-md-12">
         <div class="box">
             <div class="box-header with-border">
-                <h3 class="box-title">List of alerts ({{$vm.list.total || 0}} of {{alertEvents.count}})</h3>
+                <h3 class="box-title">List of alerts ({{$vm.list.total || 0}} of {{(alertEvents.New.count || 0)  + (alertEvents.Updated.count || 0)}})</h3>
             </div>
             <div class="box-body">
                 <div ng-include="'views/partials/alert/list/toolbar.html'"></div>
```

**Comment by nadouani** [comment] 2017-09-08 13:38
This patch will not display the full total count of alerts, because it doesn't take into account the `Imported` and `Ignored` alerts

**Comment by nadouani** [comment] 2017-09-13 13:52
I'm going to close this issue, and please feel free to reopen it if you are able to reproduce it. Thanks

**Closed by nadouani** 2017-09-13 13:52 UTC
Labels: bug, invalid

**Comment by Rolinh** [comment] 2017-12-28 08:47
It seems that when an alert is marked as read, then the alerts list is no longer refreshed. The user has to navigate away from the alerts section and back to see the updated list.

I'm sure this bug is real and not "invalid" as labeled so... let's reopen it? The updated information about how to reproduce should help finding the root cause.
