### ISSUE TITLE
History of activities performed in a Case

### ISSUE THREAD

**Issue by pottapitot** [CERT-BDF/TheHive#333] opened 2017-10-11 17:00 UTC
### Request Type
Feature Request

Is it possible to have a history tab in the case which shows the list of actions performed (with user who performed the change and what time along with the old value and new value) on the case similar to JIRA e.g. all the tasks added/deleted, observables added/removed/modified, changes in the details section?

**Comment by nadouani** [comment] 2017-10-12 09:20
Hello, this is what we call, Case timeline here https://github.com/CERT-BDF/TheHive/issues/84.

I'll mark this issue as duplicate of #84 

Thanks

**Closed by nadouani** 2017-10-12 09:20 UTC
Labels: duplicate
