### ISSUE TITLE
Remove deleted cases from database

### ISSUE THREAD

**Issue by srilumpa** [CERT-BDF/TheHive#339] opened 2017-10-13 09:13 UTC
### Request Type
Feature Request

Hi @nadouani and team,

First, this might be considered as a duplicate of #100. I didn't want to hijack the thread with my question so I created a new issue. If you consider it as a duplicate I will close this one and develop my question in #100.

Can you tell us what are your plans about deleted cases? Currently they are only tagged as `Deleted` but are kept in the database alongside their tasks and artifacts. The issue for us is that we don't want the database to grow forever and thus we need to execute from time to time some purge.

Will you embed the purge functionality directly in TheHive?

A way to implement this would be to remove from the database cases flagged as `Deleted` after a configurable period of time has passed (a duration in seconds or milliseconds, for example). That configuration would have also two specific value:
* one meaning immediately (`0` for example)
* an other one meaning never (`-1` for example)

Best regards.

**Comment by Rolinh** [comment] 2017-10-13 09:30
Hi,

Just my two cents here.

If storage really is a problem, there is always simple solutions like using a [Delete By Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) from a cronjob. Data is stored in elasticsearch after all.

IMHO, building such things into TheHive itself would bring unnecessary complexity for something that (I guess) is not even a concern for most users.

**Comment by nadouani** [comment] 2017-10-13 13:41
Hello guys,

Deleting a case seems to be more requested as we thought.
We will consider adding an administrative API to delete a case, or to purge deleted case.

This is in fact a duplicate of #100 so, I'll close this issue, and we can keep discussing on #100.

Thanks

**Closed by nadouani** 2017-10-13 13:41 UTC
Labels: duplicate
