### ISSUE TITLE
Virustotal - More meaningful error message

### ISSUE THREAD

**Issue by CERT-Bund** [CERT-BDF/TheHive#177] opened 2017-04-13 12:07 UTC
### Request Type
Enhancement

### Problem Description
We use a public Virustotal API key for our test system. The public API keys are very limited, e.g. they have a rate limit for querying the Virustotal API.
We hit the rate limit.
-> TheHive show an error message: Bad status : 204
Raw
{
  "errorMessage": "Bad status : 204",
  "success": false
}

### Possible Solutions
It would have been helpful, if the the analyzer would have displayed the reason for the error message. According to the Virustotal API documentation, Status 204 means "API rate limit exceeded"

**Comment by nadouani** [comment] 2017-04-13 12:12
Closing this one since the issue is related to Cortex-Analyzers repo

**Closed by nadouani** 2017-04-13 12:12 UTC
Labels: invalid
