### ISSUE TITLE
Elasticsearch 5.x roadmap?

### ISSUE THREAD

**Issue by mthlvt** [CERT-BDF/TheHive#82] opened 2017-01-11 10:42 UTC
### Request Type
Feature Request

### Request
Do you have any plan to support elasticsearch 5.x backend in the future? Thanks

**Comment by nadouani** [comment] 2017-01-16 09:29
Hello @mthlvt, we didn't yet planed to support ES5, but as far I know, it's easier to move from ES2 to ES5 than from 1.X to version 2.

We will give it a try as soon as we can and let you know.

**Comment by mthIvt** [comment] 2017-01-17 10:48
Ok, you can close.

**Comment by To-om** [comment] 2017-03-03 10:10
Support of ES5 requires Netty 4.1.x which is incompatible with Play 2.5.x.
We must wait Play 2.6 to add support of ES5.

**Comment by mback2k** [comment] 2017-08-31 10:34
Any news about the plans to support ES5? Play 2.6 has been released in June 2017.

**Comment by nadouani** [comment] 2017-08-31 11:11
Hello, this will be released on 2.13.0, which is the next version that will be released.

**Comment by nadouani** [comment] 2017-08-31 11:12
Closing this one, as duplicate of https://github.com/CERT-BDF/TheHive/issues/275

**Closed by nadouani** 2017-08-31 11:12 UTC
Labels: duplicate
