### ISSUE TITLE
Allow browsing in the history of live-stream

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#378] opened 2017-11-23 11:18 UTC
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 2.13.2
| Package Type              | DEB

### Problem Description
Especially when you run several analyzers on an observable, relevant infromation of the live-stream is disappears fast.

### Possible Solutions
I think it is usefull to configure which events appear on the lifestream or alternatively allow browsing to older Events.

**Comment by nadouani** [comment] 2017-11-27 09:44
This is in fact a duplicate of #84

**Closed by nadouani** 2017-11-27 09:44 UTC
Labels: duplicate
